DROP TYPE IF EXISTS monster_feature_type, crime_status_type, feature_type, item_type, order_status_type, place_type, punishment_type, sex_type, system_role_type, visit_role_type cascade;

DROP TABLE IF EXISTS MONSTER_TYPE, MONSTER, CHARACTER, ADDRESS, LIVING_PLACE, CRIME_SCENE, CRIME, CRIME_VISIT, VICTIM, SUSPECT, CRIMINAL_CASE, CLUE, SUSPECT_CLUE, INVESTIGATOR, PROFILE, BANK_ACCOUNT, VISIT_PARTICIPANT, CASE_ORDER, ITEM, ITEM_CART, INVENTORY, HISTORY, TRAP_CASE, TRAP_ITEM, ITEM_MONSTER, EQUIPMENT_CASE, CONTENTION, INVESTIGATOR_CRIME cascade;
